# Generated by Django 4.2.4 on 2023-09-03 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_profesor_cursos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'ordering': ('nombre', '-camada'), 'verbose_name': 'curso'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name': 'profesor', 'verbose_name_plural': 'profesores'},
        ),
        migrations.AlterUniqueTogether(
            name='cursos',
            unique_together={('nombre', 'camada')},
        ),
    ]
