# Generated by Django 4.2.4 on 2023-09-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_alter_cursos_options_alter_profesor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
    ]
